### PR TITLE
Use node-hid 0.7.7+ for Electron compatibility

### PR DESCRIPTION
**Pull request by soatok**
See https://github.com/node-hid/node-hid/issues/293

### CODE REVIEW

**Comment by soatok** [comment]
Also, this might warrant your attention sooner-than-later:

```
added 911 packages from 731 contributors and audited 4118 packages in 46.711s
found 202 vulnerabilities (96 low, 100 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by soatok** [comment]
Hmm, looks like it's still failing. I'm not entirely sure what the problem is.

**Comment by soatok** [comment]
@Lange This pull request should fix the compatibility issues with Electron 4.x and newer. It took a bit of trial and error, but most of the problem came down to stale dependencies and `.travis.yml`.

**Comment by Lange** [comment]
Hi @soatok, thanks for this PR!

Does this address the issues with driver selection on Linux? I.e., does it let us use `libusb` instead of forcing us to use `hidraw`? ([More context here](https://github.com/Lange/node-elgato-stream-deck/pull/51#issuecomment-385270000))

**Comment by soatok** [comment]
I don't have `hidraw` installed in my test environment, and it wouldn't compile without `libusb`

 I'm not sure if that helps if both are installed.

I also sent a separate PR (https://github.com/node-hid/node-hid/pull/304) to `node-hid` to allow me to precompile it for specific platforms (e.g. [here](https://github.com/soatok/fursona-sticker-switcher/blob/master/packaging/build-windows.sh)) rather than expect my users to have a C compiler on hand.

With that in mind, I *might* be able to help if it's still a problem.

**Comment by soatok** [comment]
Upon digging, it looks like you can specify the driver as a command line argument when building: https://github.com/node-hid/node-hid/issues/292#issuecomment-464255222

**Comment by soatok** [comment]
Upon further examination, the issue that prevented selecting libusb instead of hidraw at runtime [was fixed in v0.7.1](https://github.com/node-hid/node-hid/issues/242#issuecomment-358389355).

The [relevant section of the node-hid README](https://github.com/node-hid/node-hid#linux-notes) is a little out of date, but it mentions the `--driver=libusb` flag as well.

**Comment by soatok** [comment]
I opened https://github.com/node-hid/node-hid/pull/305 to update the README. If there's still another underlying issue, the node-hid devs will probably mention them in that thread.

But if my upstream PRs get merged, there should be no more blocking issues for my PR here.

**Comment by Julusian** [comment]
Waiting on node-hid 0.7.9 to be released then updating it should be resolved https://github.com/node-hid/node-hid/issues/309

**Comment by Julusian** [comment]
master is now using 0.7.9

**Comment by soatok** [comment]
Great. When will we see a new release?

**Comment by Julusian** [comment]
@soatok Hopefully once I have finished support for the XL :) https://github.com/Lange/node-elgato-stream-deck/pull/66

**Pull request closed without merging**
