### PR TITLE
bug(hid): Fix inability to send HID large messages

### PR DESCRIPTION
**Pull request by wuest**
First off, thanks for doing this work!  I recently purchased a Stream Deck intending to build control software under Linux, and this so far has saved me _gobs_ of time!

That said, I did find that my Stream Deck (firmware `1.0.170118` out of the box, then updated to `1.0.170133`) would not work with your tooling.  After some troubleshooting on my own project, I found that the Stream Deck now appears to want to receive no more than 4 KiB of data at once, and doesn't want the end of writes to buttons to be null padded.  Since it might be relevant, my system is as follows:
```
Arch Linux, running 4.15.15-1-ARCH
hidapi 0.8.0rc1 and libusb 1.0.22 installed from official packages
Only udev rule installed sets all Elgato Stream Decks to 0666 permissions
```

This is my first time really touching javascript; I am pretty sure that my modifications to `write` are suboptimal.  Hopefully doing the dance from Buffer to Array, then back to Buffer is unnecessary.

### CODE REVIEW

**Comment by Lange** [comment]
Hello! 👋 Thanks for this PR!

This is an interesting issue. I currently develop primarily on Windows, which is likely why I hadn't encountered these Linux problems. This PR seems to fail on Windows with the following error:

```
Error: Cannot write to HID device
    at StreamDeck.write (C:\Users\vanca\Documents\Programming\elgato-stream-deck\index.js:146:17)
    at StreamDeck._writePage1 (C:\Users\vanca\Documents\Programming\elgato-stream-deck\index.js:329:15)
    at StreamDeck.fillImage (C:\Users\vanca\Documents\Programming\elgato-stream-deck\index.js:211:8)
    at sharp.flatten.resize.raw.toBuffer.then.buffer (C:\Users\vanca\Documents\Programming\elgato-stream-deck\index.js:230:17)
    at <anonymous>
```

Additionally, the existing behavior seems to be okay for firmware versions `1.0.170118` and `1.0.170133` on Windows. Perhaps we've stumbled across a case where the behavior is somehow different on Linux?

I'll see if I can find some time to throw Linux on a laptop and test it locally, to help get to the bottom of this issue.

**Comment by wuest** [comment]
That *does* make this an interesting bug!  On my end I'll find some time to test under a couple other distros to see if the failure/success characteristics are consistent across kernel/libusb/hidapi versions.

Is there anything beyond what I've listed so far that you think will be particularly useful for troubleshooting this one?

**Comment by wuest** [comment]
Haha, no worries -- I'm a huge Javascript and Windows noob, myself.

I can confirm that the behaviors I observed locally under Arch are replicated on Ubuntu 16.04 - so this breakage is likely to have existed on the host side for two years.  Since you verified that the firmware versions I've been able to test work as expected with the codebase as it stands under Windows, I'm starting to think that we're seeing a weird incompatibility in the two USB HID stacks. :/

**Comment by Lange** [comment]
When first writing this library, I remember testing against a Raspberry Pi 3 running a standard Raspian distribution, and the library worked as expected. From that, I assumed that it would work across all Linux distros. I wonder if is still works in Raspian, or if this issue is also present there. If so, I'd then wonder how or why it ever worked to begin with.

I can probably dig up my Raspberry Pi 3 tonight and give that a shot.

**Comment by Lange** [comment]
Alright, just tested on my Raspberry Pi 3, and the behavior is the exact inverse of Windows:

For all tests, I am using [`examples/fill-button-when-pressed.js`](https://github.com/Lange/node-elgato-stream-deck/blob/master/examples/fill-button-when-pressed.js).
- On Windows, the `4k_chunk` branch errors with `Cannot write to HID device` when a button is pressed or released. It behaves fine on the `master` branch.
- On Raspbian, the `4k_chunk` branch is fine, and the `master` branch errors with `Cannot write to HID device` when a button is pressed or released.

I'm now pretty confused, because this definitely did work on Raspbian at some point. Maybe it was a very old firmware?

**Comment by Lange** [comment]
macOS has its own unique behavor:
- `master` works as expected
- `4k_chunk` does not crash, but does not work as expected. It has the output shown in the image below:
img_20180404_175332

**Comment by wuest** [comment]
Found it!
* In https://github.com/Lange/node-elgato-stream-deck/commit/9e5f3386f70730d5299146350cee38f0faebb681 the `node-hid` dependency was bumped from `0.5.7` to `0.7.2`
* In https://github.com/node-hid/node-hid/commit/39af6a937a5339247c62c25e768cc12ea8cba151 the default driver was moved from `libusb` to `hidraw`.

I've checked out 3a18f8159b17054b37152f4a8d8edb9e14df6864 and I can verify that both unit tests and functional tests work under Linux as expected.  So, my naive hypothesis:
`hidraw`, to quote the kernel documentation, "should be used if the userspace application knows exactly how to communicate with the hardware device, and is able to construct the HID
reports manually."  I suspect that non-`hidraw` interfaces "helpfully" munge the communication you're sending to the device such that it automatically breaks up chunks and ignores null padding.

If this is correct, the best course of action would most likely be one of:
 * Pin to `node-hid` a version pre-0.7.2
 * Predicate building of the payloads to send the Stream Deck on the platform under which the library is running

**Comment by Lange** [comment]
Ahh okay, that makes sense. Good work finding the root cause!

The author of `node-hid` seems to recommend `0.5.7` if `libusb` is desired, but that release does not include prebuild binaries for Node 8, which is a bummer. `0.6.0` does include prebuilt binaries for Node 8, but I'm unsure why `0.5.7` is recommended over it.

**Comment by Lange** [comment]
I've tested this library with `node-hid@0.6.0` locally on Windows and Linux, and it seems okay. @wuest, can you verify that `0.6.0` also works as expected for you? If so, I'll go ahead and push a commit which pins `node-hid` to `0.6.0` for now, until `node-hid` allows us to specify which driver we want to use (`libusb` or `hidraw`).

**Comment by wuest** [comment]
I've verified that `0.6.0` works as expected. :+1:

**Pull request closed without merging**
