### PR TITLE
feat: Add close method to cleanly close the HID device

### PR DESCRIPTION
**Pull request by natcl**

### CODE REVIEW

**Comment by natcl** [comment]
Thanks that was fast !
I wrapped the library in Node-RED and without calling close the Node-RED process would hang forever.

**Comment by Julusian** [comment]
I have just published v3.1.0 which includes this

**Comment by natcl** [comment]
Many thanks !


--
lecaude.com 
studioimaginaire.com

**Comment by natcl** [comment]
Just wanted to say thanks for this fix, just finished implementing my Node-RED wrapper and it works great !
image

**Pull request merged**
